from pyspark.sql.types import StructType, StructField, StringType, DoubleType, TimestampType, LongType
from pyspark.sql import SparkSession
from pyspark.sql.functions import lit
from datetime import datetime

# Initialize Spark session
spark = SparkSession.builder.appName("TestDataGeneration").getOrCreate()

# Define schema for purgo_playground.supplier_invoice_orig
supplier_invoice_orig_schema = StructType([
    StructField("src_sys_cd", StringType(), True),
    StructField("po_nbr", StringType(), True),
    StructField("po_line_nbr", StringType(), True),
    StructField("invc_co_amt", DoubleType(), True),
    StructField("invc_txn_amt", DoubleType(), True),
    StructField("invc_txn_type", StringType(), True),
    StructField("document_type", StringType(), True),
    StructField("document_desc", StringType(), True),
    StructField("invc_entry_period", LongType(), True),
    StructField("vchr_nbr", LongType(), True),
    StructField("fscl_yr_nbr", LongType(), True),
    StructField("vchr_type_cd", StringType(), True),
    StructField("po_curncy_cd", StringType(), True),
    StructField("post_yr_mth_nbr", LongType(), True),
    StructField("invc_entry_dt", LongType(), True),
    StructField("paymt_due_dt", LongType(), True),
    StructField("txn_curncy_mth_rt", LongType(), True),
    StructField("inv_line_desc", StringType(), True),
    StructField("spend_type_cd", StringType(), True),
    StructField("supplier_cd", StringType(), True),
    StructField("suplr_invc_dt", LongType(), True),
    StructField("txn_orig_id", StringType(), True),
    StructField("suplr_invc_nbr", StringType(), True),
    StructField("remit_to_rgn_cd", StringType(), True),
    StructField("remit_to_rgn_nm", StringType(), True),
    StructField("suplr_paymt_terms_desc", StringType(), True),
    StructField("ap_payment_term_desc", StringType(), True),
    StructField("remit_to_cntry_nm", StringType(), True),
    StructField("supplier_type_cd", StringType(), True),
    StructField("suplr_paymt_terms_cd", StringType(), True),
    StructField("ap_payment_term_cd", StringType(), True),
    StructField("remit_to_addr_line_2", StringType(), True),
    StructField("remit_to_addr_line_3", StringType(), True),
    StructField("remit_to_addr_line_4", StringType(), True),
    StructField("remit_to_cntry_cd", StringType(), True),
    StructField("po_paymt_terms_cd", StringType(), True),
    StructField("po_paymt_terms_desc", StringType(), True),
    StructField("gl_acct_id", StringType(), True),
    StructField("cost_centre_cd", LongType(), True),
    StructField("co_cd", LongType(), True),
    StructField("co_curncy_cd", StringType(), True),
    StructField("pass_through_field", StringType(), True),
    StructField("pass_through_line", StringType(), True),
    StructField("item_nbr", StringType(), True),
    StructField("item_desc", StringType(), True),
    StructField("uom_conv_factor", StringType(), True),
    StructField("invc_uom_cd", StringType(), True),
    StructField("vendor_mat_no", StringType(), True),
    StructField("unit_prc", DoubleType(), True),
    StructField("invc_qty", LongType(), True),
    StructField("base_qty", StringType(), True),
    StructField("suplr_nm_src", StringType(), True),
    StructField("remit_to_st_cd", StringType(), True),
    StructField("part_rev_no", StringType(), True),
    StructField("contract_flag", StringType(), True),
    StructField("contract_type", StringType(), True),
    StructField("profit_cntr", StringType(), True),
    StructField("co_curncy_mth_rt", LongType(), True),
    StructField("invc_txn_pmar_amt", LongType(), True),
    StructField("invc_co_pmar_amt", LongType(), True),
    StructField("unit_prc_pmar_amt", StringType(), True),
    StructField("aprval_dt", StringType(), True),
    StructField("vomi_flag", StringType(), True),
    StructField("payment_compliance_flg", StringType(), True),
    StructField("vchr_line_nbr", LongType(), True),
    StructField("vchr_status", StringType(), True),
    StructField("thermo_item_nbr", StringType(), True),
    StructField("lcr_flag", StringType(), True),
    StructField("lcr_region", StringType(), True),
    StructField("invc_apprv_id", StringType(), True),
    StructField("reporting_site", StringType(), True),
    StructField("warehouse", StringType(), True),
    StructField("warehouse_nm", StringType(), True),
    StructField("unit", StringType(), True),
    StructField("nature", StringType(), True),
    StructField("inv_flg", StringType(), True),
    StructField("contract_start_date", StringType(), True),
    StructField("contract_end_date", StringType(), True),
    StructField("fk_orig", StringType(), True),
    StructField("floor_stock_cd", StringType(), True),
    StructField("sec_supp_cd", StringType(), True),
    StructField("rpt_flex1", StringType(), True),
    StructField("supplier_segment", StringType(), True),
    StructField("inv_flg_text", StringType(), True),
    StructField("invc_txn_amt_clsfctn", StringType(), True),
    StructField("source_country", StringType(), True),
    StructField("business_unit", StringType(), True),
    StructField("div_cd", StringType(), True)
])

# Generate test data
test_data = [
    # Happy path
    {
        "src_sys_cd": "SYS1",
        "po_nbr": "PO12345",
        "po_line_nbr": "001",
        "invc_co_amt": 1500.75,
        "invc_txn_amt": 1500.75,
        "invc_txn_type": "Purchase",
        "document_type": "DT1",
        "document_desc": "Invoice for PO12345",
        "invc_entry_period": 202403,
        "vchr_nbr": 1001,
        "fscl_yr_nbr": 2024,
        "vchr_type_cd": "VTC1",
        "po_curncy_cd": "USD",
        "post_yr_mth_nbr": 202404,
        "invc_entry_dt": 20240321,
        "paymt_due_dt": 20240421,
        "txn_curncy_mth_rt": 1,
        "inv_line_desc": "Line item description",
        "spend_type_cd": "STC1",
        "supplier_cd": "SUPP001",
        "suplr_invc_dt": 20240321,
        "txn_orig_id": "TXN123",
        "suplr_invc_nbr": "INV1001",
        "remit_to_rgn_cd": "RC1",
        "remit_to_rgn_nm": "Region1",
        "suplr_paymt_terms_desc": "Net 30",
        "ap_payment_term_desc": "30 days",
        "remit_to_cntry_nm": "USA",
        "supplier_type_cd": "TypeA",
        "suplr_paymt_terms_cd": "NET30",
        "ap_payment_term_cd": "30D",
        "remit_to_addr_line_2": "Suite 100",
        "remit_to_addr_line_3": None,
        "remit_to_addr_line_4": None,
        "remit_to_cntry_cd": "US",
        "po_paymt_terms_cd": "PP1",
        "po_paymt_terms_desc": "Terms1",
        "gl_acct_id": "GL1001",
        "cost_centre_cd": 5001,
        "co_cd": 4001,
        "co_curncy_cd": "USD",
        "pass_through_field": None,
        "pass_through_line": None,
        "item_nbr": "ITEM001",
        "item_desc": "Item Description",
        "uom_conv_factor": "1",
        "invc_uom_cd": "EA",
        "vendor_mat_no": "MAT001",
        "unit_prc": 1500.75,
        "invc_qty": 1,
        "base_qty": "1",
        "suplr_nm_src": "Supplier Inc.",
        "remit_to_st_cd": "NY",
        "part_rev_no": "PR001",
        "contract_flag": "Y",
        "contract_type": "CT1",
        "profit_cntr": "PC1",
        "co_curncy_mth_rt": 1,
        "invc_txn_pmar_amt": 0,
        "invc_co_pmar_amt": 0,
        "unit_prc_pmar_amt": "0",
        "aprval_dt": "20240322",
        "vomi_flag": "N",
        "payment_compliance_flg": "Y",
        "vchr_line_nbr": 10,
        "vchr_status": "Active",
        "thermo_item_nbr": "THERM001",
        "lcr_flag": "L",
        "lcr_region": "LR1",
        "invc_apprv_id": "APPROVED",
        "reporting_site": "Site1",
        "warehouse": "WH1",
        "warehouse_nm": "Warehouse1",
        "unit": "Unit1",
        "nature": "Nature1",
        "inv_flg": "I",
        "contract_start_date": "2024-01-01",
        "contract_end_date": "2025-01-01",
        "fk_orig": "FK1",
        "floor_stock_cd": "FS1",
        "sec_supp_cd": "SSC1",
        "rpt_flex1": "RF1",
        "supplier_segment": "SS1",
        "inv_flg_text": "Flagged",
        "invc_txn_amt_clsfctn": "Classification1",
        "source_country": "USA",
        "business_unit": "BU1",
        "div_cd": "DIV1"
    },
    # Edge case: Maximum values
    {
        "src_sys_cd": "SYS_MAX",
        "po_nbr": "PO_MAX",
        "po_line_nbr": "999",
        "invc_co_amt": 9999999999.99,
        "invc_txn_amt": 9999999999.99,
        "invc_txn_type": "MaxPurchase",
        "document_type": "DT_MAX",
        "document_desc": "Invoice with maximum values",
        "invc_entry_period": 999912,
        "vchr_nbr": 9999999999,
        "fscl_yr_nbr": 9999,
        "vchr_type_cd": "VTC_MAX",
        "po_curncy_cd": "CUR_MAX",
        "post_yr_mth_nbr": 999912,
        "invc_entry_dt": 99991231,
        "paymt_due_dt": 99991231,
        "txn_curncy_mth_rt": 999999,
        "inv_line_desc": "Maximum line description",
        "spend_type_cd": "ST_MAX",
        "supplier_cd": "SUPP_MAX",
        "suplr_invc_dt": 99991231,
        "txn_orig_id": "TXN_MAX",
        "suplr_invc_nbr": "INV_MAX",
        "remit_to_rgn_cd": "RC_MAX",
        "remit_to_rgn_nm": "RegionMax",
        "suplr_paymt_terms_desc": "Net Maximum",
        "ap_payment_term_desc": "Maximum days",
        "remit_to_cntry_nm": "MaxCountry",
        "supplier_type_cd": "TypeMax",
        "suplr_paymt_terms_cd": "NETMAX",
        "ap_payment_term_cd": "MAXD",
        "remit_to_addr_line_2": "Suite Max",
        "remit_to_addr_line_3": None,
        "remit_to_addr_line_4": None,
        "remit_to_cntry_cd": "MX",
        "po_paymt_terms_cd": "PP_MAX",
        "po_paymt_terms_desc": "TermsMax",
        "gl_acct_id": "GL_MAX",
        "cost_centre_cd": 9999999999,
        "co_cd": 9999999999,
        "co_curncy_cd": "CUR_MAX",
        "pass_through_field": None,
        "pass_through_line": None,
        "item_nbr": "ITEM_MAX",
        "item_desc": "Maximum Item Description",
        "uom_conv_factor": "999",
        "invc_uom_cd": "MAXEA",
        "vendor_mat_no": "MAT_MAX",
        "unit_prc": 9999999999.99,
        "invc_qty": 9999999999,
        "base_qty": "999",
        "suplr_nm_src": "Supplier Max Inc.",
        "remit_to_st_cd": "MX",
        "part_rev_no": "PR_MAX",
        "contract_flag": "Y",
        "contract_type": "CT_MAX",
        "profit_cntr": "PC_MAX",
        "co_curncy_mth_rt": 999999,
        "invc_txn_pmar_amt": 9999999999,
        "invc_co_pmar_amt": 9999999999,
        "unit_prc_pmar_amt": "999",
        "aprval_dt": "99991231",
        "vomi_flag": "Y",
        "payment_compliance_flg": "N",
        "vchr_line_nbr": 9999999999,
        "vchr_status": "Inactive",
        "thermo_item_nbr": "THERM_MAX",
        "lcr_flag": "LM",
        "lcr_region": "LR_MAX",
        "invc_apprv_id": "APPROVED_MAX",
        "reporting_site": "SiteMax",
        "warehouse": "WH_MAX",
        "warehouse_nm": "WarehouseMax",
        "unit": "UnitMax",
        "nature": "NatureMax",
        "inv_flg": "IMAX",
        "contract_start_date": "9999-12-31",
        "contract_end_date": "9999-12-31",
        "fk_orig": "FK_MAX",
        "floor_stock_cd": "FS_MAX",
        "sec_supp_cd": "SSC_MAX",
        "rpt_flex1": "RF_MAX",
        "supplier_segment": "SS_MAX",
        "inv_flg_text": "FlaggedMax",
        "invc_txn_amt_clsfctn": "ClassificationMax",
        "source_country": "MAX",
        "business_unit": "BUMAX",
        "div_cd": "DIV_MAX"
    },
    # Error case: Negative amounts
    {
        "src_sys_cd": "SYS_NEG",
        "po_nbr": "PO_NEG",
        "po_line_nbr": "002",
        "invc_co_amt": -1500.75,
        "invc_txn_amt": -1500.75,
        "invc_txn_type": "Return",
        "document_type": "DT_NEG",
        "document_desc": "Invoice with negative amounts",
        "invc_entry_period": 202403,
        "vchr_nbr": 1002,
        "fscl_yr_nbr": 2024,
        "vchr_type_cd": "VTC_NEG",
        "po_curncy_cd": "USD",
        "post_yr_mth_nbr": 202404,
        "invc_entry_dt": 20240322,
        "paymt_due_dt": 20240422,
        "txn_curncy_mth_rt": -1,
        "inv_line_desc": "Negative line description",
        "spend_type_cd": "ST_NEG",
        "supplier_cd": "SUPP_NEG",
        "suplr_invc_dt": 20240322,
        "txn_orig_id": "TXN_NEG",
        "suplr_invc_nbr": "INV1002",
        "remit_to_rgn_cd": "RC_NEG",
        "remit_to_rgn_nm": "RegionNeg",
        "suplr_paymt_terms_desc": "Net -30",
        "ap_payment_term_desc": "-30 days",
        "remit_to_cntry_nm": "USA",
        "supplier_type_cd": "TypeNeg",
        "suplr_paymt_terms_cd": "NET-30",
        "ap_payment_term_cd": "-30D",
        "remit_to_addr_line_2": "Suite Neg",
        "remit_to_addr_line_3": None,
        "remit_to_addr_line_4": None,
        "remit_to_cntry_cd": "US",
        "po_paymt_terms_cd": "PP_NEG",
        "po_paymt_terms_desc": "TermsNeg",
        "gl_acct_id": "GL_NEG",
        "cost_centre_cd": 5002,
        "co_cd": 4002,
        "co_curncy_cd": "USD",
        "pass_through_field": None,
        "pass_through_line": None,
        "item_nbr": "ITEM_NEG",
        "item_desc": "Negative Item Description",
        "uom_conv_factor": "-1",
        "invc_uom_cd": "NEG",
        "vendor_mat_no": "MAT_NEG",
        "unit_prc": -1500.75,
        "invc_qty": -1,
        "base_qty": "-1",
        "suplr_nm_src": "Supplier Neg Inc.",
        "remit_to_st_cd": "NY",
        "part_rev_no": "PR_NEG",
        "contract_flag": "N",
        "contract_type": "CT_NEG",
        "profit_cntr": "PC_NEG",
        "co_curncy_mth_rt": -1,
        "invc_txn_pmar_amt": -1,
        "invc_co_pmar_amt": -1,
        "unit_prc_pmar_amt": "-1",
        "aprval_dt": "20240323",
        "vomi_flag": "Y",
        "payment_compliance_flg": "N",
        "vchr_line_nbr": 11,
        "vchr_status": "Inactive",
        "thermo_item_nbr": "THERM_NEG",
        "lcr_flag": "LN",
        "lcr_region": "LR_NEG",
        "invc_apprv_id": "APPROVED_NEG",
        "reporting_site": "SiteNeg",
        "warehouse": "WH_NEG",
        "warehouse_nm": "WarehouseNeg",
        "unit": "UnitNeg",
        "nature": "NatureNeg",
        "inv_flg": "INEG",
        "contract_start_date": "2024-02-01",
        "contract_end_date": "2025-02-01",
        "fk_orig": "FK_NEG",
        "floor_stock_cd": "FS_NEG",
        "sec_supp_cd": "SSC_NEG",
        "rpt_flex1": "RF_NEG",
        "supplier_segment": "SS_NEG",
        "inv_flg_text": "FlaggedNeg",
        "invc_txn_amt_clsfctn": "ClassificationNeg",
        "source_country": "USA",
        "business_unit": "BU_NEG",
        "div_cd": "DIV_NEG"
    },
    # NULL handling
    {
        "src_sys_cd": None,
        "po_nbr": None,
        "po_line_nbr": None,
        "invc_co_amt": None,
        "invc_txn_amt": None,
        "invc_txn_type": None,
        "document_type": None,
        "document_desc": None,
        "invc_entry_period": None,
        "vchr_nbr": None,
        "fscl_yr_nbr": None,
        "vchr_type_cd": None,
        "po_curncy_cd": None,
        "post_yr_mth_nbr": None,
        "invc_entry_dt": None,
        "paymt_due_dt": None,
        "txn_curncy_mth_rt": None,
        "inv_line_desc": None,
        "spend_type_cd": None,
        "supplier_cd": None,
        "suplr_invc_dt": None,
        "txn_orig_id": None,
        "suplr_invc_nbr": None,
        "remit_to_rgn_cd": None,
        "remit_to_rgn_nm": None,
        "suplr_paymt_terms_desc": None,
        "ap_payment_term_desc": None,
        "remit_to_cntry_nm": None,
        "supplier_type_cd": None,
        "suplr_paymt_terms_cd": None,
        "ap_payment_term_cd": None,
        "remit_to_addr_line_2": None,
        "remit_to_addr_line_3": None,
        "remit_to_addr_line_4": None,
        "remit_to_cntry_cd": None,
        "po_paymt_terms_cd": None,
        "po_paymt_terms_desc": None,
        "gl_acct_id": None,
        "cost_centre_cd": None,
        "co_cd": None,
        "co_curncy_cd": None,
        "pass_through_field": None,
        "pass_through_line": None,
        "item_nbr": None,
        "item_desc": None,
        "uom_conv_factor": None,
        "invc_uom_cd": None,
        "vendor_mat_no": None,
        "unit_prc": None,
        "invc_qty": None,
        "base_qty": None,
        "suplr_nm_src": None,
        "remit_to_st_cd": None,
        "part_rev_no": None,
        "contract_flag": None,
        "contract_type": None,
        "profit_cntr": None,
        "co_curncy_mth_rt": None,
        "invc_txn_pmar_amt": None,
        "invc_co_pmar_amt": None,
        "unit_prc_pmar_amt": None,
        "aprval_dt": None,
        "vomi_flag": None,
        "payment_compliance_flg": None,
        "vchr_line_nbr": None,
        "vchr_status": None,
        "thermo_item_nbr": None,
        "lcr_flag": None,
        "lcr_region": None,
        "invc_apprv_id": None,
        "reporting_site": None,
        "warehouse": None,
        "warehouse_nm": None,
        "unit": None,
        "nature": None,
        "inv_flg": None,
        "contract_start_date": None,
        "contract_end_date": None,
        "fk_orig": None,
        "floor_stock_cd": None,
        "sec_supp_cd": None,
        "rpt_flex1": None,
        "supplier_segment": None,
        "inv_flg_text": None,
        "invc_txn_amt_clsfctn": None,
        "source_country": None,
        "business_unit": None,
        "div_cd": None
    },
    # Special characters and multi-byte characters
    {
        "src_sys_cd": "SYS@#",
        "po_nbr": "PO!@#",
        "po_line_nbr": "00😊",
        "invc_co_amt": 1234.56,
        "invc_txn_amt": 1234.56,
        "invc_txn_type": "Purch©ase",
        "document_type": "DT😊",
        "document_desc": "Invoice with special chars 🚀",
        "invc_entry_period": 202405,
        "vchr_nbr": 1003,
        "fscl_yr_nbr": 2025,
        "vchr_type_cd": "VTC@#",
        "po_curncy_cd": "€¥",
        "post_yr_mth_nbr": 202406,
        "invc_entry_dt": 20240515,
        "paymt_due_dt": 20240615,
        "txn_curncy_mth_rt": 1,
        "inv_line_desc": "Description with emojis 😃🔥",
        "spend_type_cd": "ST@#",
        "supplier_cd": "SUPP😊",
        "suplr_invc_dt": 20240515,
        "txn_orig_id": "TXN@#",
        "suplr_invc_nbr": "INV@#😊",
        "remit_to_rgn_cd": "RC@#",
        "remit_to_rgn_nm": "Región😊",
        "suplr_paymt_terms_desc": "Net 30🔥",
        "ap_payment_term_desc": "30 días",
        "remit_to_cntry_nm": "México🇲🇽",
        "supplier_type_cd": "Typê😊",
        "suplr_paymt_terms_cd": "NET30🔥",
        "ap_payment_term_cd": "30D😊",
        "remit_to_addr_line_2": "Suite 🚀",
        "remit_to_addr_line_3": None,
        "remit_to_addr_line_4": None,
        "remit_to_cntry_cd": "MX😊",
        "po_paymt_terms_cd": "PP@#",
        "po_paymt_terms_desc": "Terms🔥",
        "gl_acct_id": "GL@#😊",
        "cost_centre_cd": 5003,
        "co_cd": 4003,
        "co_curncy_cd": "USD🔥",
        "pass_through_field": None,
        "pass_through_line": None,
        "item_nbr": "ITEM@#😊",
        "item_desc": "Item Desc🔥😊",
        "uom_conv_factor": "1🔥",
        "invc_uom_cd": "EA🔥",
        "vendor_mat_no": "MAT@#😊",
        "unit_prc": 1234.56,
        "invc_qty": 2,
        "base_qty": "2🔥",
        "suplr_nm_src": "Supplier 🚀 Inc.",
        "remit_to_st_cd": "CA🔥",
        "part_rev_no": "PR@#😊",
        "contract_flag": "Y🔥",
        "contract_type": "CT@#😊",
        "profit_cntr": "PC🔥",
        "co_curncy_mth_rt": 1,
        "invc_txn_pmar_amt": 0,
        "invc_co_pmar_amt": 0,
        "unit_prc_pmar_amt": "0🔥",
        "aprval_dt": "20240516",
        "vomi_flag": "N🔥",
        "payment_compliance_flg": "Y🔥",
        "vchr_line_nbr": 12,
        "vchr_status": "Active🔥",
        "thermo_item_nbr": "THERM@#😊",
        "lcr_flag": "L🔥",
        "lcr_region": "LR@#😊",
        "invc_apprv_id": "APPROVED🔥",
        "reporting_site": "Site🔥",
        "warehouse": "WH🔥",
        "warehouse_nm": "Warehouse🔥",
        "unit": "Unit🔥",
        "nature": "Nature🔥",
        "inv_flg": "I🔥",
        "contract_start_date": "2024-03-01",
        "contract_end_date": "2025-03-01",
        "fk_orig": "FK@#😊",
        "floor_stock_cd": "FS🔥",
        "sec_supp_cd": "SSC@#😊",
        "rpt_flex1": "RF🔥",
        "supplier_segment": "SS@#😊",
        "inv_flg_text": "Flagged🔥",
        "invc_txn_amt_clsfctn": "Classification🔥",
        "source_country": "USA🔥",
        "business_unit": "BU🔥",
        "div_cd": "DIV@#😊"
    },
    # Additional records can be added here to reach 20-30 entries
]

# Create DataFrame
df_test = spark.createDataFrame(data=test_data, schema=supplier_invoice_orig_schema)

# Display DataFrame
df_test.show(truncate=False)

# Write DataFrame to target table with try-except block
try:
    df_test.write.mode("overwrite").format("delta").saveAsTable("purgo_playground.supplier_invoice_orig_test")
except Exception as e:
    print(f"Error writing test data: {e}")