from datetime import datetime
from pyspark.sql import SparkSession
from pyspark.sql.types import (
    StructType, StructField, StringType, DoubleType, LongType, TimestampType, DecimalType
)
from pyspark.sql import functions as F

# Initialize Spark session
spark = SparkSession.builder \
    .appName("TestDataGeneration") \
    .getOrCreate()

# Schema for supplier_invoice_bkp
schema_supplier_invoice_bkp = StructType([
    StructField("src_sys_cd", StringType(), True),
    StructField("po_nbr", StringType(), True),
    StructField("po_line_nbr", StringType(), True),
    StructField("invc_co_amt", DoubleType(), True),
    StructField("invc_txn_amt", DoubleType(), True),
    StructField("invc_txn_type", StringType(), True),
    StructField("document_type", StringType(), True),
    StructField("document_desc", StringType(), True),
    StructField("invc_entry_period", LongType(), True),
    StructField("vchr_nbr", LongType(), True),
    StructField("fscl_yr_nbr", LongType(), True),
    StructField("vchr_type_cd", StringType(), True),
    StructField("po_curncy_cd", StringType(), True),
    StructField("post_yr_mth_nbr", LongType(), True),
    StructField("invc_entry_dt", LongType(), True),
    StructField("paymt_due_dt", LongType(), True),
    StructField("txn_curncy_mth_rt", LongType(), True),
    StructField("inv_line_desc", StringType(), True),
    StructField("spend_type_cd", StringType(), True),
    StructField("supplier_cd", StringType(), True),
    StructField("suplr_invc_dt", LongType(), True),
    StructField("txn_orig_id", StringType(), True),
    StructField("suplr_invc_nbr", StringType(), True),
    StructField("remit_to_rgn_cd", StringType(), True),
    StructField("remit_to_rgn_nm", StringType(), True),
    StructField("suplr_paymt_terms_desc", StringType(), True),
    StructField("ap_payment_term_desc", StringType(), True),
    StructField("remit_to_cntry_nm", StringType(), True),
    StructField("suppSupplier Type Cd", StringType(), True),
    StructField("suplr_paymt_terms_cd", StringType(), True),
    StructField("ap_paympentcd", StringType(), True),
    StructField("remit_to_addr_line_2", StringType(), True),
    StructField("remit_to_addr_line_3", StringType(), True),
    StructField("remit_to_addr_line_4", StringType(), True),
    StructField("remit_to_cntry_cd", StringType(), True),
    StructField("po_paymt_terms_cd", StringType(), True),
    StructField("po_paymt_terms_desc", StringType(), True),
    StructField("gl_acct_id", StringType(), True),
    StructField("cost_centre_cd", LongType(), True),
    StructField("co_cd", LongType(), True),
    StructField("co_curncy_cd", StringType(), True),
    StructField("pass_through_field", StringType(), True),
    StructField("pass_through_line", StringType(), True),
    StructField("item_nbr", StringType(), True),
    StructField("item_desc", StringType(), True),
    StructField("uom_conv_factor", StringType(), True),
    StructField("invc_uom_cd", StringType(), True),
    StructField("vendor_mat_no", StringType(), True),
    StructField("unit_prc", DoubleType(), True),
    StructField("invc_qty", LongType(), True),
    StructField("base_qty", StringType(), True),
    StructField("suplr_nm_src", StringType(), True),
    StructField("remit_to_st_cd", StringType(), True),
    StructField("part_rev_no", StringType(), True),
    StructField("contract_flag", StringType(), True),
    StructField("contract_type", StringType(), True),
    StructField("profit_cntr", StringType(), True),
    StructField("co_curncy_mth_rt", LongType(), True),
    StructField("invc_txn_pmar_amt", LongType(), True),
    StructField("invc_co_pmar_amt", LongType(), True),
    StructField("unit_prc_pmar_amt", StringType(), True),
    StructField("aprval_dt", StringType(), True),
    StructField("vomi_flag", StringType(), True),
    StructField("payment_compliance_flg", StringType(), True),
    StructField("vchr_line_nbr", LongType(), True),
    StructField("vchr_status", StringType(), True),
    StructField("thermo_item_nbr", StringType(), True),
    StructField("lcr_flag", StringType(), True),
    StructField("lcr_region", StringType(), True),
    StructField("invc_apprv_id", StringType(), True),
    StructField("reporting_site", StringType(), True),
    StructField("warehouse", StringType(), True),
    StructField("warehouse_nm", StringType(), True),
    StructField("unit", StringType(), True),
    StructField("nature", StringType(), True),
    StructField("inv_flg", StringType(), True),
    StructField("contract_start_date", StringType(), True),
    StructField("contract_end_date", StringType(), True),
    StructField("fk_orig", StringType(), True),
    StructField("floor_stock_cd", StringType(), True),
    StructField("sec_supp_cd", StringType(), True),
    StructField("rpt_flex1", StringType(), True),
    StructField("supplier_segment", StringType(), True),
    StructField("inv_flg_text", StringType(), True),
    StructField("invc_txn_amt_clsfctn", StringType(), True),
    StructField("source_country", StringType(), True),
    StructField("business_unit", StringType(), True),
    StructField("div_cd", StringType(), True),
])

# Example test data generation
data_supplier_invoice_bkp = [
    {
        "src_sys_cd": "SYSTEM1",
        "po_nbr": "PO123456",
        "po_line_nbr": "LINE1",
        "invc_co_amt": 500.0,
        "invc_txn_amt": 550.0,
        "invc_txn_type": "PURCHASE",
        "document_type": "INVOICE",
        "document_desc": "Testing invoice description",
        "invc_entry_period": 202303,
        "vchr_nbr": 987654321,
        "fscl_yr_nbr": 2023,
        "vchr_type_cd": "CREDIT",
        "po_curncy_cd": "USD",
        "post_yr_mth_nbr": 202303,
        "invc_entry_dt": 20230315,
        "paymt_due_dt": 20230330,
        "txn_curncy_mth_rt": 0,
        "inv_line_desc": "Line item description",
        "spend_type_cd": "INDIRECT",
        "supplier_cd": "SUPPLIER123",
        "suplr_invc_dt": 20230315,
        "txn_orig_id": "TXN001",
        "suplr_invc_nbr": "INV001",
        "remit_to_rgn_cd": None,
        "remit_to_rgn_nm": None,
        "suplr_paymt_terms_desc": "DESCRIPTION",
        "ap_payment_term_desc": "TERM_DESC",
        "remit_to_cntry_nm": "USA",
        "supplier_type_cd": "TYPE1",
        "suplr_paymt_terms_cd": "TERMCD1",
        "ap_payment_term_cd": "APTERMCD1",
        "remit_to_addr_line_2": None,
        "remit_to_addr_line_3": None,
        "remit_to_addr_line_4": None,
        "remit_to_cntry_cd": None,
        "po_paymt_terms_cd": None,
        "po_paymt_terms_desc": None,
        "gl_acct_id": "GL_ACCOUNT_123",
        "cost_centre_cd": 12345,
        "co_cd": 54321,
        "co_curncy_cd": "USD",
        "pass_through_field": None,
        "pass_through_line": None,
        "item_nbr": None,
        "item_desc": None,
        "uom_conv_factor": None,
        "invc_uom_cd": None,
        "vendor_mat_no": None,
        "unit_prc": 500.0,
        "invc_qty": 1,
        "base_qty": None,
        "suplr_nm_src": None,
        "remit_to_st_cd": "ST123",
        "part_rev_no": None,
        "contract_flag": None,
        "contract_type": None,
        "profit_cntr": None,
        "co_curncy_mth_rt": 0,
        "invc_txn_pmar_amt": 0,
        "invc_co_pmar_amt": 0,
        "unit_prc_pmar_amt": None,
        "aprval_dt": None,
        "vomi_flag": None,
        "payment_compliance_flg": None,
        "vchr_line_nbr": 1,
        "vchr_status": "APPROVED",
        "thermo_item_nbr": None,
        "lcr_flag": None,
        "lcr_region": None,
        "invc_apprv_id": None,
        "reporting_site": None,
        "warehouse": None,
        "warehouse_nm": None,
        "unit": None,
        "nature": None,
        "inv_flg": None,
        "contract_start_date": None,
        "contract_end_date": None,
        "fk_orig": None,
        "floor_stock_cd": None,
        "sec_supp_cd": None,
        "rpt_flex1": None,
        "supplier_segment": None,
        "inv_flg_text": None,
        "invc_txn_amt_clsfctn": None,
        "source_country": "NA",
        "business_unit": None,
        "div_cd": "DIV001",
    }
    # Add more test cases here following similar structure for diverse data range
]

# Create DataFrame using test data
df_supplier_invoice_bkp = spark.createDataFrame(data_supplier_invoice_bkp, schema_supplier_invoice_bkp)

# Show DataFrame
df_supplier_invoice_bkp.show()

# Note: Add additional DataFrame creation logic for other tables as needed following similar pattern.