
CREATE TABLE Cateries (
  CateryID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  CateryName STRING(15) NOT NULL,
  Description STRING NULL,
  Picture BINARY NULL
)
USING DELTA;

ALTER TABLE Cateries ADD CONSTRAINT PK_Cateries PRIMARY KEY (CateryID);
