CREATE TABLE Cateries (
    CateryID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CateryName STRING(15) NOT NULL,
    Description STRING, 
    Picture BINARY,
    PRIMARY KEY (CateryID)
)