CREATE TABLE Shippers (
  ShipperID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1), 
  CompanyName STRING NOT NULL, 
  Phone STRING
);

ALTER TABLE Shippers ADD CONSTRAINT PK_Shippers PRIMARY KEY (ShipperID);