
CREATE TABLE tpcds.call_center (
	cc_call_center_sk INTEGER NOT NULL, 
	cc_call_center_id CHAR(16) NOT NULL, 
	cc_rec_start_date DATE, 
	cc_rec_end_date DATE, 
	cc_closed_date_sk INTEGER, 
	cc_open_date_sk INTEGER, 
	cc_name VARCHAR(50), 
	cc_class VARCHAR(50), 
	cc_employees INTEGER, 
	cc_sq_ft INTEGER, 
	cc_hours CHAR(20), 
	cc_manager VARCHAR(40), 
	cc_mkt_id INTEGER, 
	cc_mkt_class CHAR(50), 
	cc_mkt_desc VARCHAR(100), 
	cc_market_manager VARCHAR(40), 
	cc_division INTEGER, 
	cc_division_name VARCHAR(50), 
	cc_company INTEGER, 
	cc_company_name CHAR(50), 
	cc_street_number CHAR(10), 
	cc_street_name VARCHAR(60), 
	cc_street_type CHAR(15), 
	cc_suite_number CHAR(10), 
	cc_city VARCHAR(60), 
	cc_county VARCHAR(30), 
	cc_state CHAR(2), 
	cc_zip CHAR(10), 
	cc_country VARCHAR(20), 
	cc_gmt_offset NUMERIC(5, 2), 
	cc_tax_percentage NUMERIC(5, 2), 
	CONSTRAINT call_center_pkey PRIMARY KEY (cc_call_center_sk)
) DISTSTYLE ALL

