
CREATE TABLE tpcds.catalog_returns (
	cr_returned_date_sk INTEGER, 
	cr_returned_time_sk INTEGER, 
	cr_item_sk INTEGER NOT NULL, 
	cr_refunded_customer_sk INTEGER, 
	cr_refunded_cdemo_sk INTEGER, 
	cr_refunded_hdemo_sk INTEGER, 
	cr_refunded_addr_sk INTEGER, 
	cr_returning_customer_sk INTEGER, 
	cr_returning_cdemo_sk INTEGER, 
	cr_returning_hdemo_sk INTEGER, 
	cr_returning_addr_sk INTEGER, 
	cr_call_center_sk INTEGER, 
	cr_catalog_page_sk INTEGER, 
	cr_ship_mode_sk INTEGER, 
	cr_warehouse_sk INTEGER, 
	cr_reason_sk INTEGER, 
	cr_order_number BIGINT NOT NULL, 
	cr_return_quantity INTEGER, 
	cr_return_amount NUMERIC(7, 2), 
	cr_return_tax NUMERIC(7, 2), 
	cr_return_amt_inc_tax NUMERIC(7, 2), 
	cr_fee NUMERIC(7, 2), 
	cr_return_ship_cost NUMERIC(7, 2), 
	cr_refunded_cash NUMERIC(7, 2), 
	cr_reversed_charge NUMERIC(7, 2), 
	cr_store_credit NUMERIC(7, 2), 
	cr_net_loss NUMERIC(7, 2), 
	CONSTRAINT catalog_returns_pkey PRIMARY KEY (cr_item_sk, cr_order_number)
) DISTSTYLE KEY DISTKEY (cr_item_sk) SORTKEY (cr_returned_date_sk)

