
CREATE TABLE tpcds.catalog_sales (
	cs_sold_date_sk INTEGER, 
	cs_sold_time_sk INTEGER, 
	cs_ship_date_sk INTEGER, 
	cs_bill_customer_sk INTEGER, 
	cs_bill_cdemo_sk INTEGER, 
	cs_bill_hdemo_sk INTEGER, 
	cs_bill_addr_sk INTEGER, 
	cs_ship_customer_sk INTEGER, 
	cs_ship_cdemo_sk INTEGER, 
	cs_ship_hdemo_sk INTEGER, 
	cs_ship_addr_sk INTEGER, 
	cs_call_center_sk INTEGER, 
	cs_catalog_page_sk INTEGER, 
	cs_ship_mode_sk INTEGER, 
	cs_warehouse_sk INTEGER, 
	cs_item_sk INTEGER NOT NULL, 
	cs_promo_sk INTEGER, 
	cs_order_number BIGINT NOT NULL, 
	cs_quantity INTEGER, 
	cs_wholesale_cost NUMERIC(7, 2), 
	cs_list_price NUMERIC(7, 2), 
	cs_sales_price NUMERIC(7, 2), 
	cs_ext_discount_amt NUMERIC(7, 2), 
	cs_ext_sales_price NUMERIC(7, 2), 
	cs_ext_wholesale_cost NUMERIC(7, 2), 
	cs_ext_list_price NUMERIC(7, 2), 
	cs_ext_tax NUMERIC(7, 2), 
	cs_coupon_amt NUMERIC(7, 2), 
	cs_ext_ship_cost NUMERIC(7, 2), 
	cs_net_paid NUMERIC(7, 2), 
	cs_net_paid_inc_tax NUMERIC(7, 2), 
	cs_net_paid_inc_ship NUMERIC(7, 2), 
	cs_net_paid_inc_ship_tax NUMERIC(7, 2), 
	cs_net_profit NUMERIC(7, 2), 
	CONSTRAINT catalog_sales_pkey PRIMARY KEY (cs_item_sk, cs_order_number)
) DISTSTYLE KEY DISTKEY (cs_item_sk) SORTKEY (cs_sold_date_sk)

