
CREATE TABLE tpcds.date_dim (
	d_date_sk INTEGER NOT NULL, 
	d_date_id CHAR(16) NOT NULL, 
	d_date DATE, 
	d_month_seq INTEGER, 
	d_week_seq INTEGER, 
	d_quarter_seq INTEGER, 
	d_year INTEGER, 
	d_dow INTEGER, 
	d_moy INTEGER, 
	d_dom INTEGER, 
	d_qoy INTEGER, 
	d_fy_year INTEGER, 
	d_fy_quarter_seq INTEGER, 
	d_fy_week_seq INTEGER, 
	d_day_name CHAR(9), 
	d_quarter_name CHAR(6), 
	d_holiday CHAR(1), 
	d_weekend CHAR(1), 
	d_following_holiday CHAR(1), 
	d_first_dom INTEGER, 
	d_last_dom INTEGER, 
	d_same_day_ly INTEGER, 
	d_same_day_lq INTEGER, 
	d_current_day CHAR(1), 
	d_current_week CHAR(1), 
	d_current_month CHAR(1), 
	d_current_quarter CHAR(1), 
	d_current_year CHAR(1), 
	CONSTRAINT date_dim_pkey PRIMARY KEY (d_date_sk)
) DISTSTYLE ALL

