
CREATE TABLE Shippers (
  ShipperID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  CompanyName STRING NOT NULL,
  Phone STRING
)
USING DELTA;
ALTER TABLE Shippers ADD CONSTRAINT PK_Shippers PRIMARY KEY (ShipperID);
